spin_manifest_version = 2

[application]
authors = ["Venca H <venca.hyncica@gmail.com>"]
description = "Simple primes app"
name = "primes"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "primes"

[component.primes]
source = "app.wasm"
[component.primes.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
