spin_manifest_version = 2

[application]
name = "primes"
version = "0.1.0"
authors = ["Venca H <venca.hyncica@gmail.com>"]
description = "simple app for searching for primes"

[[trigger.http]]
route = "/..."
component = "primes"

[component.primes]
source = "target/wasm32-wasi/release/primes.wasm"
allowed_outbound_hosts = []
[component.primes.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
