spin_manifest_version = 2

[application]
authors = ["gabaj"]
description = "Primes"
name = "my-primes-project"
version = "0.1.0"

[[trigger.http]]
route = "/primes"
component = "my-primes-project"

[component.my-primes-project]
source = "target/my-primes-project.wasm"
exclude_files = ["**/node_modules"]
[component.my-primes-project.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]