spin_manifest_version = 2

[application]
name = "hello-world"
version = "0.1.0"
authors = ["Venca H <venca.hyncica@gmail.com>"]
description = "simple hello world app"

[[trigger.http]]
route = "/..."
component = "hello-world"

[component.hello-world]
source = "target/wasm32-wasip1/release/hello_world.wasm"
allowed_outbound_hosts = []
[component.hello-world.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
