spin_manifest_version = 2

[application]
name = "fibonacci"
version = "0.1.0"
authors = ["Venca H <venca.hyncica@gmail.com>"]
description = "simple fibonacci app"

[[trigger.http]]
route = "/..."
component = "fibonacci"

[component.fibonacci]
source = "target/wasm32-wasip1/release/fibonacci.wasm"
allowed_outbound_hosts = []
[component.fibonacci.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
