---
- name: Run container
  hosts: all
  vars_prompt:

    - name: docker_image
      prompt: "Insert name of docker image"
      private: no

  tasks:

    - name: Pull Docker image
      community.docker.docker_image_pull:
        name: "ghcr.io/vencah/{{ docker_image }}"
    
