spin_manifest_version = 2

[application]
authors = ["Venca H <venca.hyncica@gmail.com>"]
description = "Simple fibonacci app"
name = "fibonacci"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "fibonacci"

[component.fibonacci]
source = "app.wasm"
[component.fibonacci.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
