spin_manifest_version = 2

[application]
authors = ["JiriGaba <155835908+JiGaba@users.noreply.github.com>"]
description = "Fibonaciho posloupnost"
name = "my-fibonacci-project"
version = "0.1.0"

[[trigger.http]]
route = "/fibonacci"
component = "my-fibonacci-project"

[component.my-fibonacci-project]
source = "target/my-fibonacci-project.wasm"
exclude_files = ["**/node_modules"]
[component.my-fibonacci-project.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]