name: Spin-typescript-build

on:
  push:
    tags: ['spin-typescript']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ak9si_final_project-spin-typescript
  USER_NAME: vencah

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout the code repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            code/SPIN/TypeScript
          path: ./common/spin-typescript-mock
          token: ${{ secrets.GH_PAT }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: js2wasm 

      - name: component dependency hello-world
        run: npm install
        working-directory: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-hello-world
  
      - name: build and push hello-world
        id: push_hello-world
        uses: fermyon/actions/spin/push@v1
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_TOKEN }}
          registry_reference: "ghcr.io${{ env.REPOSITORY }}/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}/spin-typescript-hello-world"
          manifest_file: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-hello-world/spin.toml
          
      - name: component dependency fibonacci
        run: npm install
        working-directory: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-fibonacci-project

      - name: build and push fibonacci app
        id: push_fibonacci
        uses: fermyon/actions/spin/push@v1
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_TOKEN }}
          registry_reference: "ghcr.io${{ env.REPOSITORY }}/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}/spin-typescript-fibonacci"
          manifest_file: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-fibonacci-project/spin.toml

      - name: component dependency primes
        run: npm install
        working-directory: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-primes-project

      - name: build and push primes
        id: push_primes
        uses: fermyon/actions/spin/push@v1
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_TOKEN }}
          registry_reference: "ghcr.io${{ env.REPOSITORY }}/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}/spin-typescript-primes"
          manifest_file: ./common/spin-typescript-mock/code/SPIN/TypeScript/my-primes-project/spin.toml
